name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push (no cache)
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/barracuda-camera-streamer:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/barracuda-camera-streamer:latest
